### ISSUE TITLE
Update on Artifacting Fix?

### ISSUE THREAD

**Issue by BungleHerJungle** [PolarWizard/BorderlandsGOTYEnhancedFix#1]
Can't find any updates, so just wanting to see if there's a ballpark on fixing the artifacting issue above 21:9 :) rest of it works GREAT, no issues.

**Comment by PolarWizard** [comment]
There is no ETA on it as I am not actively working on this anymore.
I am traveling for work currently so I wont be around for a while to look at this again, you may wanna see if anyone on wsgf site or discord wants to try to tackle it.

**Comment by PolarWizard** [comment]
This has been addressed and fixed in v2.0.0.
Please try the new release and close this issue 😄 
If not closed within a week, I shall close this issue as fixed myself.

**Comment by BungleHerJungle** [comment]
It works!! thank you so much my friend!
