### ISSUE TITLE
No Weapon Zoom at 32:9 Resolutions

### ISSUE THREAD

**Issue by BungleHerJungle** [PolarWizard/BorderlandsGOTYEnhancedFix#2]
Seems like weapon scopes just become a 1x overlay instead of zooming at 5120x1440, consistent from snipers to smgs.

**Comment by PolarWizard** [comment]
This has been addressed and fixed in v2.0.0.
Please try the new release and close this issue 😄 
If not closed within a week, I shall close this issue as fixed myself.

**Comment by BungleHerJungle** [comment]
Perfect!
