### ISSUE TITLE
Feature request: Option to clamp max FOV (eg when sprinting)

### ISSUE THREAD

**Issue by Lagahan** [PolarWizard/BorderlandsGOTYEnhancedFix#3]
FOV when sprinting becomes a bit ridiculous at high base FOVs (106 shown here):

https://github.com/user-attachments/assets/fdfcde9c-323b-45da-b324-140b10913d63

FWIW this happened with the original game as well using other FOV fixes & I realize this is a result of fixing the other 32:9 issue of scopes not zooming correctly, just wondering if clamping is feasible.

**Comment by PolarWizard** [comment]
Yeah its a consequence of how they implemented this functionality. The bigger your FOV the more exponential the camera drawback will be when sprinting, its a fixed range unfortunately.
I'll check this out and see what I can do about it 😄

**Comment by PolarWizard** [comment]
Feature added in latest release: https://github.com/PolarWizard/BorderlandsGOTYEnhancedFix/releases/tag/v2.1.0
Please try latest release and confirm feature works as expected and close this issue as resolved😄

**Comment by Lagahan** [comment]
Works great, his fixes an issue I've had with this game since 2011 playing the original on nv surround!
I didn't notice last night but the spawn warp was also broken (camera went inverted), this fixes that too

Fix disabled, 106 fov:

https://github.com/user-attachments/assets/83a81c5c-cbe1-460e-828a-b606af3bd83e

Fix enabled, 106 fov, 0.5 scale:

https://github.com/user-attachments/assets/e8689c9f-2204-4c46-8034-3005791f51fd
